### ISSUE TITLE
Can I use PCNtoolkit to create normative models of EEG Data?

### ISSUE THREAD

**Issue by adavidBlancoUPF** [predictive-clinical-neuroscience/PCNtoolkit-demo#14]
Hi, thank you very much for all your work. I've been going through your paper (Rutherford et al., 2022) and it looks like most of the use examples of the toolkit seem to be thought to deal with MRI data. I was expecting it to also work with extracted features from EEG data, do you think there could be any issue with that? Just to know before I start going deep into learning its usage. Thanks!

**Comment by amarquand** [comment]
Hi - yes, it should be possible to use normative models for EEG and there is work going on in this direction. You would just need to ensure that your data are in csv format and choose an appropriate model for your data
