### ISSUE TITLE
"mY = mY[m]" (line 772) in normative.py causes "IndexError: list index out of range"

### ISSUE THREAD

**Issue by hughmt** [predictive-clinical-neuroscience/PCNtoolkit-demo#5]
Hi there, I'm testing out your pcntoolkit for a project of mine and I'm excited to see how it runs, so thanks for making this package available.

However when running [pcntoolkit/normative.py](https://github.com/amarquand/PCNtoolkit/blob/master/pcntoolkit/normative.py) I encountered an error on line 772 (& subsequently 773 should it be allowed to continue running); specifically, 
`IndexError: list index out of range`

I examined the meta data file and found that meta_data['mean_resp'] and meta_data['std_resp'] are arrays stored in lists, having len=1 for both, so when item "m" in mY is indexed on line 772 it throws this error (in the case that len(models)>1).

What is the expected behaviour here?

Why is it that model evaluation only occurs on the final model (m=the final item in enumerate(models))? Shouldn't this model evaluation occur within a similar loop:
`for i, m in enumerate(models):`

In which case the lines 771-773 aren't needed and line 788 should be changed to:
`results = evaluate(Y, Yhat, S2=S2, mY=mY[0][m], sY=sY[0][m])`

Thanks again for the package! Let me know if I can provide any additional info.

**Comment by amarquand** [comment]
Hi - I think this is a known bug that we recently fixed. Could you please upgrade to the latest version of PCNtoolkit (on the dev branch), or alternatively downgrade to v0.21. I think that will fix your problem
