### ISSUE TITLE
Imports not working for the BLR_normativemodel_protocol.ipynb tutorial

### ISSUE THREAD

**Issue by Andjelaaaa** [predictive-clinical-neuroscience/PCNtoolkit-demo#6]
Hi,

While going through the BLR_normativemodel_protocol jupyter notebook, I noticed a small issue; the PCN toolkit imports weren't working. As pointed out by my colleague @likeajumprope, the error is the same as a [previously encountered issue](https://github.com/amarquand/PCNtoolkit/issues/90). 
Hence, the solution is just to change the default python version on Google Colab from 3.7 to 3.9 (or 3.8+) before running the 
`! pip install -r requirements.txt` line of code.

Thank you for these great tutorials,

Andjela Dimitrijevic

**Comment by saigerutherford** [comment]
Thanks for pointing this out, and apologies for the slow reply! This issue has been fixed by adding the version number of the toolkit to requirements.txt
