### ISSUE TITLE
HBR SHASH with latest version of the toolkit 

### ISSUE THREAD

**Issue by aimanoli** [predictive-clinical-neuroscience/PCNtoolkit-demo#7]
Hello,

Many thanks for your work on this toolkit! I've been trying out the HBR SHASH tutorial, and it doesn't seem to work with the latest version of the toolkit (0.28). Moreover, downgrading to the older version used in the tutorial (0.25) creates a lot of dependency-related conflicts. Are you planning to update the tutorial for the current version of PCNToolkit (or update the toolkit itself)?

Best,
Katerina

**Comment by AuguB** [comment]
Thanks for the reminder. I updated the tutorial, it now runs with version 0.28.

**Comment by AuguB** [comment]
Thanks for the reminder. I updated the tutorial, it now runs with version 0.28.
